import prisma from "@/lib/prisma";
import { NextResponse } from "next/server";

const wordData = [
  {
    chapterId: "clmn4k21k0000znlzy5604qps",
    origin: "a, ac, ad",
    meaningOfOrigin: "~쪽으로(to)",
    word: "achieve",
    meaning: "달성하다, 이루다 획득하다",
  },
  {
    chapterId: "clmn4k21k0000znlzy5604qps",
    origin: "a, ac, ad",
    meaningOfOrigin: "~쪽으로(to)",
    word: "accept",
    meaning: "받아들이다, 인정하다",
  },
  {
    chapterId: "clmn4k21k0000znlzy5604qps",
    origin: "a, ac, ad",
    meaningOfOrigin: "~쪽으로(to)",
    word: "accuse",
    meaning: "고발하다, 비난하다",
  },
  {
    chapterId: "clmn4k21k0000znlzy5604qps",
    origin: "a, ac, ad",
    meaningOfOrigin: "~쪽으로(to)",
    word: "adopt",
    meaning: "입약하다, 채택하다",
  },
  {
    chapterId: "clmn4k21k0000znlzy5604qps",
    origin: "a, ac, ad",
    meaningOfOrigin: "~쪽으로(to)",
    word: "admire",
    meaning: "감탄하다, 존경하다",
  },
  {
    chapterId: "clmn4mgth0001znlz5c1j3fhb",
    origin: "de",
    meaningOfOrigin: "아래로",
    word: "depress",
    meaning: "우울하게하다, 불경기가되다",
  },
  {
    chapterId: "clmn4mgth0001znlz5c1j3fhb",
    origin: "de",
    meaningOfOrigin: "아래로",
    word: "depend",
    meaning: "의존하다",
  },
  {
    chapterId: "clmn4mgth0001znlz5c1j3fhb",
    origin: "de",
    meaningOfOrigin: "아래로",
    word: "describe",
    meaning: "묘사하다, 설명하다",
  },
  {
    chapterId: "clmn4mgth0001znlz5c1j3fhb",
    origin: "de",
    meaningOfOrigin: "아래로",
    word: "degrade",
    meaning: "저하시키다, 비하하다",
  },
  {
    chapterId: "clmn4mgth0001znlz5c1j3fhb",
    origin: "de",
    meaningOfOrigin: "아래로",
    word: "descend",
    meaning: "내려오다(가다)",
  },
  {
    chapterId: "clmn4mgth0002znlz92k3fsgy",
    origin: "sub",
    meaningOfOrigin: "아래",
    word: "submarine",
    meaning: "잠수함, 해저의",
  },
  {
    chapterId: "clmn4mgth0002znlz92k3fsgy",
    origin: "sub",
    meaningOfOrigin: "아래",
    word: "subject",
    meaning: "과목, 주제",
  },
  {
    chapterId: "clmn4mgth0002znlz92k3fsgy",
    origin: "sub",
    meaningOfOrigin: "아래",
    word: "subscribe",
    meaning: "구독하다, 기부하다",
  },
  {
    chapterId: "clmn4mgth0002znlz92k3fsgy",
    origin: "sub",
    meaningOfOrigin: "아래",
    word: "substitute",
    meaning: "대신하다, 대체물",
  },
  {
    chapterId: "clmn4mgth0002znlz92k3fsgy",
    origin: "sub",
    meaningOfOrigin: "아래",
    word: "substance",
    meaning: "본질(핵심), 물질",
  },
  {
    chapterId: "clmn4mgth0003znlzp6pclo78",
    origin: "under",
    meaningOfOrigin: "아래에",
    word: "underground",
    meaning: "지하의",
  },
  {
    chapterId: "clmn4mgth0003znlzp6pclo78",
    origin: "under",
    meaningOfOrigin: "아래에",
    word: "undergo",
    meaning: "겪다, 견디다(참다)",
  },
  {
    chapterId: "clmn4mgth0003znlzp6pclo78",
    origin: "under",
    meaningOfOrigin: "아래에",
    word: "undervalue",
    meaning: "과소평가하다, 너무 적게 잡다",
  },
  {
    chapterId: "clmn4mgth0003znlzp6pclo78",
    origin: "under",
    meaningOfOrigin: "아래에",
    word: "undermine",
    meaning: "~의 밑을 파다, 약화시키다",
  },
  {
    chapterId: "clmn4mgth0003znlzp6pclo78",
    origin: "under",
    meaningOfOrigin: "아래에",
    word: "underlie",
    meaning: "~의 아래에 있다, 기초가 되다",
  },
  {
    chapterId: "clmn4mgth0004znlz2l59dfk1",
    origin: "sur",
    meaningOfOrigin: "위에",
    word: "surface",
    meaning: "표면, 외관",
  },
  {
    chapterId: "clmn4mgth0004znlz2l59dfk1",
    origin: "sur",
    meaningOfOrigin: "위에",
    word: "survive",
    meaning: "살아남다, 생존하다",
  },
  {
    chapterId: "clmn4mgth0004znlz2l59dfk1",
    origin: "sur",
    meaningOfOrigin: "위에",
    word: "survey",
    meaning: "조사하다, 조사",
  },
  {
    chapterId: "clmn4mgth0004znlz2l59dfk1",
    origin: "sur",
    meaningOfOrigin: "위에",
    word: "surplus",
    meaning: "과잉, 잉여",
  },
  {
    chapterId: "clmn4mgth0004znlz2l59dfk1",
    origin: "sur",
    meaningOfOrigin: "위에",
    word: "surpass",
    meaning: "뛰어넘다, 능가하다",
  },
  {
    chapterId: "clmn4mgti0005znlz24ab91rq",
    origin: "up",
    meaningOfOrigin: "위로",
    word: "upgrade",
    meaning: "향상시키다, 등급을 올리다",
  },
  {
    chapterId: "clmn4mgti0005znlz24ab91rq",
    origin: "up",
    meaningOfOrigin: "위로",
    word: "update",
    meaning: "갱신하다, 최근 정보를 알려주다",
  },
  {
    chapterId: "clmn4mgti0005znlz24ab91rq",
    origin: "up",
    meaningOfOrigin: "위로",
    word: "upset",
    meaning: "속상하게 하다, 속상한",
  },
  {
    chapterId: "clmn4mgti0005znlz24ab91rq",
    origin: "up",
    meaningOfOrigin: "위로",
    word: "upload",
    meaning: "(컴퓨터) 업로드하다",
  },
  {
    chapterId: "clmn4mgti0005znlz24ab91rq",
    origin: "up",
    meaningOfOrigin: "위로",
    word: "uphold",
    meaning: "떠받치다, (법, 원칙) 유지시키다",
  },
  {
    chapterId: "clmn4mgti0006znlzj9vv4o2n",
    origin: "super",
    meaningOfOrigin: "위에, 초월하여",
    word: "superior",
    meaning: "우수한, 상위(상급)의",
  },
  {
    chapterId: "clmn4mgti0006znlzj9vv4o2n",
    origin: "super",
    meaningOfOrigin: "위에, 초월하여",
    word: "superb",
    meaning: "뛰어난, 최고의",
  },
  {
    chapterId: "clmn4mgti0006znlzj9vv4o2n",
    origin: "super",
    meaningOfOrigin: "위에, 초월하여",
    word: "superficial",
    meaning: "표면의, 가벼운",
  },
  {
    chapterId: "clmn4mgti0006znlzj9vv4o2n",
    origin: "super",
    meaningOfOrigin: "위에, 초월하여",
    word: "supervise",
    meaning: "(사람, 일) 감독하다",
  },
  {
    chapterId: "clmn4mgti0006znlzj9vv4o2n",
    origin: "super",
    meaningOfOrigin: "위에, 초월하여",
    word: "supernatural",
    meaning: "초자연적인, 불가사의한",
  },
  {
    chapterId: "clmn4mgti0007znlznjx8ugvr",
    origin: "over",
    meaningOfOrigin: "위에서",
    word: "overlook",
    meaning: "간과하다, 못 본 체하다",
  },
  {
    chapterId: "clmn4mgti0007znlznjx8ugvr",
    origin: "over",
    meaningOfOrigin: "위에서",
    word: "oversee",
    meaning: "감독하다",
  },
  {
    chapterId: "clmn4mgti0007znlznjx8ugvr",
    origin: "over",
    meaningOfOrigin: "위에서",
    word: "overcome",
    meaning: "(곤란) 극복하다",
  },
  {
    chapterId: "clmn4mgti0007znlznjx8ugvr",
    origin: "over",
    meaningOfOrigin: "위에서",
    word: "overwhelm",
    meaning: "제압하다, 압도하다",
  },
  {
    chapterId: "clmn4mgti0007znlznjx8ugvr",
    origin: "over",
    meaningOfOrigin: "위에서",
    word: "overtake",
    meaning: "추월하다, 능가하다",
  },
  {
    chapterId: "clmn4mgti0008znlzh54eh5fr",
    origin: "ex",
    meaningOfOrigin: "밖으로, 서로",
    word: "exchange",
    meaning: "교환하다",
  },
  {
    chapterId: "clmn4mgti0008znlzh54eh5fr",
    origin: "ex",
    meaningOfOrigin: "밖으로, 서로",
    word: "expose",
    meaning: "노출시키다",
  },
  {
    chapterId: "clmn4mgti0008znlzh54eh5fr",
    origin: "ex",
    meaningOfOrigin: "밖으로, 서로",
    word: "expand",
    meaning: "확대시키다",
  },
  {
    chapterId: "clmn4mgti0008znlzh54eh5fr",
    origin: "ex",
    meaningOfOrigin: "밖으로, 서로",
    word: "excel",
    meaning: "뛰어나다, 능가하다",
  },
  {
    chapterId: "clmn4mgti0008znlzh54eh5fr",
    origin: "ex",
    meaningOfOrigin: "밖으로, 서로",
    word: "explicit",
    meaning: "분명한",
  },
  {
    chapterId: "clmn4mgti0009znlz7tbbqz4t",
    origin: "out",
    meaningOfOrigin: "밖으로",
    word: "outgoing",
    meaning: "외향적인",
  },
  {
    chapterId: "clmn4mgti0009znlz7tbbqz4t",
    origin: "out",
    meaningOfOrigin: "밖으로",
    word: "outcome",
    meaning: "결과",
  },
  {
    chapterId: "clmn4mgti0009znlz7tbbqz4t",
    origin: "out",
    meaningOfOrigin: "밖으로",
    word: "outlook",
    meaning: "경치, (사물에 대한) 시각",
  },
  {
    chapterId: "clmn4mgti0009znlz7tbbqz4t",
    origin: "out",
    meaningOfOrigin: "밖으로",
    word: "outline",
    meaning: "윤곽",
  },
  {
    chapterId: "clmn4mgti0009znlz7tbbqz4t",
    origin: "out",
    meaningOfOrigin: "밖으로",
    word: "outstanding",
    meaning: "뛰어난",
  },
  {
    chapterId: "clmn4mgti000aznlz8kpngxtg",
    origin: "pro",
    meaningOfOrigin: "앞으로",
    word: "protect",
    meaning: "보호하다",
  },
  {
    chapterId: "clmn4mgti000aznlz8kpngxtg",
    origin: "pro",
    meaningOfOrigin: "앞으로",
    word: "propose",
    meaning: "제안하다",
  },
  {
    chapterId: "clmn4mgti000aznlz8kpngxtg",
    origin: "pro",
    meaningOfOrigin: "앞으로",
    word: "progress",
    meaning: "(앞으로) 나아가다",
  },
  {
    chapterId: "clmn4mgti000aznlz8kpngxtg",
    origin: "pro",
    meaningOfOrigin: "앞으로",
    word: "provide",
    meaning: "제공하다, 준비하다",
  },
  {
    chapterId: "clmn4mgti000aznlz8kpngxtg",
    origin: "pro",
    meaningOfOrigin: "앞으로",
    word: "promote",
    meaning: "촉진하다",
  },
  {
    chapterId: "clmn4mgti000bznlzwqcm83ij",
    origin: "fore",
    meaningOfOrigin: "앞에",
    word: "forehead",
    meaning: "이마",
  },
  {
    chapterId: "clmn4mgti000bznlzwqcm83ij",
    origin: "fore",
    meaningOfOrigin: "앞에",
    word: "forefather",
    meaning: "조상",
  },
  {
    chapterId: "clmn4mgti000bznlzwqcm83ij",
    origin: "fore",
    meaningOfOrigin: "앞에",
    word: "foresee",
    meaning: "예견하다",
  },
  {
    chapterId: "clmn4mgti000bznlzwqcm83ij",
    origin: "fore",
    meaningOfOrigin: "앞에",
    word: "foremost",
    meaning: "가장 중요한",
  },
  {
    chapterId: "clmn4mgti000bznlzwqcm83ij",
    origin: "fore",
    meaningOfOrigin: "앞에",
    word: "forecast",
    meaning: "예측",
  },
  {
    chapterId: "clmn4mgti000cznlz0cfwipte",
    origin: "pre",
    meaningOfOrigin: "먼저, 미리",
    word: "preview",
    meaning: "(영화, 쇼) 시사회",
  },
  {
    chapterId: "clmn4mgti000cznlz0cfwipte",
    origin: "pre",
    meaningOfOrigin: "먼저, 미리",
    word: "present",
    meaning: "현재의, 선물",
  },
  {
    chapterId: "clmn4mgti000cznlz0cfwipte",
    origin: "pre",
    meaningOfOrigin: "먼저, 미리",
    word: "predict",
    meaning: "예언하다, 예측(예상)하다",
  },
  {
    chapterId: "clmn4mgti000cznlz0cfwipte",
    origin: "pre",
    meaningOfOrigin: "먼저, 미리",
    word: "prescribe",
    meaning: "(약을) 처방하다",
  },
  {
    chapterId: "clmn4mgti000cznlz0cfwipte",
    origin: "pre",
    meaningOfOrigin: "먼저, 미리",
    word: "prejudice",
    meaning: "편견, 선입견",
  },
  {
    chapterId: "clmn4mgti000dznlz4rvxa2h8",
    origin: "post",
    meaningOfOrigin: "뒤에, 나중에",
    word: "postwar",
    meaning: "전후의",
  },
  {
    chapterId: "clmn4mgti000dznlz4rvxa2h8",
    origin: "post",
    meaningOfOrigin: "뒤에, 나중에",
    word: "postscript",
    meaning: "(편지의) 추신",
  },
  {
    chapterId: "clmn4mgti000dznlz4rvxa2h8",
    origin: "post",
    meaningOfOrigin: "뒤에, 나중에",
    word: "postpone",
    meaning: "뒤로 미루다, 연기하다",
  },
  {
    chapterId: "clmn4mgti000dznlz4rvxa2h8",
    origin: "post",
    meaningOfOrigin: "뒤에, 나중에",
    word: "postmodern",
    meaning: "포스트모던의, 최신 유행의",
  },
  {
    chapterId: "clmn4mgti000dznlz4rvxa2h8",
    origin: "post",
    meaningOfOrigin: "뒤에, 나중에",
    word: "posterity",
    meaning: "후세, 후대",
  },
  {
    chapterId: "clmn4mgtj000eznlzuw6yaee0",
    origin: "un",
    meaningOfOrigin: "아니다",
    word: "unable",
    meaning: "할 수 없는",
  },
  {
    chapterId: "clmn4mgtj000eznlzuw6yaee0",
    origin: "un",
    meaningOfOrigin: "아니다",
    word: "unfair",
    meaning: "불공평한",
  },
  {
    chapterId: "clmn4mgtj000eznlzuw6yaee0",
    origin: "un",
    meaningOfOrigin: "아니다",
    word: "uncommon",
    meaning: "흔하지 않은, 드문",
  },
  {
    chapterId: "clmn4mgtj000eznlzuw6yaee0",
    origin: "un",
    meaningOfOrigin: "아니다",
    word: "unstable",
    meaning: "불안정한",
  },
  {
    chapterId: "clmn4mgtj000eznlzuw6yaee0",
    origin: "un",
    meaningOfOrigin: "아니다",
    word: "unconscious",
    meaning: "의식 불명의, 의식이 없는",
  },
  {
    chapterId: "clmn4mgtj000fznlz4o23ir3m",
    origin: "re",
    meaningOfOrigin: "다시",
    word: "recover",
    meaning: "회복하다, 되찾다",
  },
  {
    chapterId: "clmn4mgtj000fznlz4o23ir3m",
    origin: "re",
    meaningOfOrigin: "다시",
    word: "replace",
    meaning: "대체(대신)하다",
  },
  {
    chapterId: "clmn4mgtj000fznlz4o23ir3m",
    origin: "re",
    meaningOfOrigin: "다시",
    word: "recycle",
    meaning: "재활용(재생)하다",
  },
  {
    chapterId: "clmn4mgtj000fznlz4o23ir3m",
    origin: "re",
    meaningOfOrigin: "다시",
    word: "reproduce",
    meaning: "번식하다",
  },
  {
    chapterId: "clmn4mgtj000fznlz4o23ir3m",
    origin: "re",
    meaningOfOrigin: "다시",
    word: "revive",
    meaning: "활기를 되찾다, (기억) 되살아나게 하다",
  },
  {
    chapterId: "clmn4mgtj000gznlzrawxqqko",
    origin: "an, anci, anti",
    meaningOfOrigin: "이전에, 앞에",
    word: "ancient",
    meaning: "고대의, 아주 오래된",
  },
  {
    chapterId: "clmn4mgtj000gznlzrawxqqko",
    origin: "an, anci, anti",
    meaningOfOrigin: "이전에, 앞에",
    word: "antique",
    meaning: "옛날의, 골동품",
  },
  {
    chapterId: "clmn4mgtj000gznlzrawxqqko",
    origin: "an, anci, anti",
    meaningOfOrigin: "이전에, 앞에",
    word: "anticipate",
    meaning: "기대하다, 예상하다",
  },
  {
    chapterId: "clmn4mgtj000gznlzrawxqqko",
    origin: "an, anci, anti",
    meaningOfOrigin: "이전에, 앞에",
    word: "ancestry",
    meaning: "가계, 혈통",
  },
  {
    chapterId: "clmn4mgtj000hznlzco4m5gj3",
    origin: "in",
    meaningOfOrigin: "~안에, 안으로",
    word: "input",
    meaning: "입력하다",
  },
  {
    chapterId: "clmn4mgtj000hznlzco4m5gj3",
    origin: "in",
    meaningOfOrigin: "~안에, 안으로",
    word: "income",
    meaning: "소득, 수입",
  },
  {
    chapterId: "clmn4mgtj000hznlzco4m5gj3",
    origin: "in",
    meaningOfOrigin: "~안에, 안으로",
    word: "induce",
    meaning: "유도하다",
  },
  {
    chapterId: "clmn4mgtj000hznlzco4m5gj3",
    origin: "in",
    meaningOfOrigin: "~안에, 안으로",
    word: "include",
    meaning: "포함하다",
  },
  {
    chapterId: "clmn4mgtj000hznlzco4m5gj3",
    origin: "in",
    meaningOfOrigin: "~안에, 안으로",
    word: "involve",
    meaning: "포함하다, 관련시키다",
  },
  {
    chapterId: "clmn4mgtj000iznlzktzres7u",
    origin: "im",
    meaningOfOrigin: "반대의",
    word: "impossible",
    meaning: "불가능한",
  },
  {
    chapterId: "clmn4mgtj000iznlzktzres7u",
    origin: "im",
    meaningOfOrigin: "반대의",
    word: "immoral",
    meaning: "부도덕한",
  },
  {
    chapterId: "clmn4mgtj000iznlzktzres7u",
    origin: "im",
    meaningOfOrigin: "반대의",
    word: "impolite",
    meaning: "예의없는, 무례한",
  },
  {
    chapterId: "clmn4mgtj000iznlzktzres7u",
    origin: "im",
    meaningOfOrigin: "반대의",
    word: "improper",
    meaning: "부적절한",
  },
  {
    chapterId: "clmn4mgtj000iznlzktzres7u",
    origin: "im",
    meaningOfOrigin: "반대의",
    word: "impartial",
    meaning: "공정한",
  },
  {
    chapterId: "clmn4mgtj000jznlz12w0537a",
    origin: "trans",
    meaningOfOrigin: "이쪽에서 저쪽으로",
    word: "translate",
    meaning: "번역하다, 통역하다",
  },
  {
    chapterId: "clmn4mgtj000jznlz12w0537a",
    origin: "trans",
    meaningOfOrigin: "이쪽에서 저쪽으로",
    word: "transplant",
    meaning: "이식하다, 옮겨 심다",
  },
  {
    chapterId: "clmn4mgtj000jznlz12w0537a",
    origin: "trans",
    meaningOfOrigin: "이쪽에서 저쪽으로",
    word: "transform",
    meaning: "변형하다, 바꾸다",
  },
  {
    chapterId: "clmn4mgtj000jznlz12w0537a",
    origin: "trans",
    meaningOfOrigin: "이쪽에서 저쪽으로",
    word: "transcribe",
    meaning: "옮겨적다, 기록하다",
  },
  {
    chapterId: "clmn4mgtj000jznlz12w0537a",
    origin: "trans",
    meaningOfOrigin: "이쪽에서 저쪽으로",
    word: "transport",
    meaning: "수송하다, 운송하다",
  },
  {
    chapterId: "clmn4mgtj000kznlzb7kssdr6",
    origin: "anti",
    meaningOfOrigin: "반대하여, 대항하여",
    word: "antiaging",
    meaning: "노화 방지의",
  },
  {
    chapterId: "clmn4mgtj000kznlzb7kssdr6",
    origin: "anti",
    meaningOfOrigin: "반대하여, 대항하여",
    word: "antisocial",
    meaning: "반사회적인",
  },
  {
    chapterId: "clmn4mgtj000kznlzb7kssdr6",
    origin: "anti",
    meaningOfOrigin: "반대하여, 대항하여",
    word: "antinuclear",
    meaning: "핵에너지 사용에 반대하는",
  },
  {
    chapterId: "clmn4mgtj000kznlzb7kssdr6",
    origin: "anti",
    meaningOfOrigin: "반대하여, 대항하여",
    word: "antinational",
    meaning: "반국가적인",
  },
  {
    chapterId: "clmn4mgtj000kznlzb7kssdr6",
    origin: "anti",
    meaningOfOrigin: "반대하여, 대항하여",
    word: "antigovernment",
    meaning: "반정부의",
  },
  {
    chapterId: "clmn4mgtj000lznlzyz2vwdma",
    origin: "counter",
    meaningOfOrigin: "대항하여, 반대하여",
    word: "counteract",
    meaning: "대응하다, 중화하다",
  },
  {
    chapterId: "clmn4mgtj000lznlzyz2vwdma",
    origin: "counter",
    meaningOfOrigin: "대항하여, 반대하여",
    word: "counterattack",
    meaning: "역습하다, 반격하다",
  },
  {
    chapterId: "clmn4mgtj000lznlzyz2vwdma",
    origin: "counter",
    meaningOfOrigin: "대항하여, 반대하여",
    word: "counterproductive",
    meaning: "비생산적인",
  },
  {
    chapterId: "clmn4mgtj000lznlzyz2vwdma",
    origin: "counter",
    meaningOfOrigin: "대항하여, 반대하여",
    word: "countermeasure",
    meaning: "대책, 대응책",
  },
  {
    chapterId: "clmn4mgtj000lznlzyz2vwdma",
    origin: "counter",
    meaningOfOrigin: "대항하여, 반대하여",
    word: "counterexample",
    meaning: "반증, 반례",
  },
  {
    chapterId: "clmn4mgtj000mznlzlha86t4b",
    origin: "mis",
    meaningOfOrigin: "잘못된",
    word: "mislead",
    meaning: "잘못 이끌다, 오도하다",
  },
  {
    chapterId: "clmn4mgtj000mznlzlha86t4b",
    origin: "mis",
    meaningOfOrigin: "잘못된",
    word: "misbehavior",
    meaning: "나쁜 행실, 버릇없음",
  },
  {
    chapterId: "clmn4mgtj000mznlzlha86t4b",
    origin: "mis",
    meaningOfOrigin: "잘못된",
    word: "misfortune",
    meaning: "불운, 불행",
  },
  {
    chapterId: "clmn4mgtj000mznlzlha86t4b",
    origin: "mis",
    meaningOfOrigin: "잘못된",
    word: "misunderstand",
    meaning: "오해하다",
  },
  {
    chapterId: "clmn4mgtj000mznlzlha86t4b",
    origin: "mis",
    meaningOfOrigin: "잘못된",
    word: "misinterpret",
    meaning: "잘못 해석(이해)하다",
  },
  {
    chapterId: "clmn4mgtj000nznlzn5hdsjzt",
    origin: "in, ter",
    meaningOfOrigin: "~사이에, ~간에",
    word: "international",
    meaning: "국제적인",
  },
  {
    chapterId: "clmn4mgtj000nznlzn5hdsjzt",
    origin: "in, ter",
    meaningOfOrigin: "~사이에, ~간에",
    word: "interdependence",
    meaning: "상호의존",
  },
  {
    chapterId: "clmn4mgtj000nznlzn5hdsjzt",
    origin: "in, ter",
    meaningOfOrigin: "~사이에, ~간에",
    word: "interaction",
    meaning: "상호작용",
  },
  {
    chapterId: "clmn4mgtj000nznlzn5hdsjzt",
    origin: "in, ter",
    meaningOfOrigin: "~사이에, ~간에",
    word: "intervene",
    meaning: "중재하다, 개입하다",
  },
  {
    chapterId: "clmn4mgtj000nznlzn5hdsjzt",
    origin: "in, ter",
    meaningOfOrigin: "~사이에, ~간에",
    word: "interfere",
    meaning: "방해하다, 간섭하다",
  },
  {
    chapterId: "clmn4mgtk000oznlzmokwykun",
    origin: "com",
    meaningOfOrigin: "함께, 같이",
    word: "combine",
    meaning: "결합하다, 합치다",
  },
  {
    chapterId: "clmn4mgtk000oznlzmokwykun",
    origin: "com",
    meaningOfOrigin: "함께, 같이",
    word: "company",
    meaning: "회사, 단체",
  },
  {
    chapterId: "clmn4mgtk000oznlzmokwykun",
    origin: "com",
    meaningOfOrigin: "함께, 같이",
    word: "complicate",
    meaning: "복잡하게 만들다",
  },
  {
    chapterId: "clmn4mgtk000oznlzmokwykun",
    origin: "com",
    meaningOfOrigin: "함께, 같이",
    word: "commerce",
    meaning: "무역, 상업",
  },
  {
    chapterId: "clmn4mgtk000oznlzmokwykun",
    origin: "com",
    meaningOfOrigin: "함께, 같이",
    word: "compromise",
    meaning: "타협",
  },
];

export async function GET() {
  const createWords = await prisma.word.createMany({
    data: wordData,
  });
  return NextResponse.json(createWords);
}
